Repository khawajaazfar2000/Hacktoberfest2022-Repository-4, pull requests merged in 2022-10, with the labels that each got.

#1 even or odd is ok now
  Check_Even_Or_Odd.cpp
  Check_Even_Or_Odd.exe
  Check_Even_Or_Odd_C++.cpp
Labels: hacktoberfest

#2 Linked List ADDED
  Linked list/.vscode/c_cpp_properties.json
  Linked list/.vscode/launch.json
  Linked list/.vscode/settings.json
  Linked list/Linked_List.cpp
  Linked list/Recursive display.cpp
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#3 Island Count by DevMittal04 for Hacktoberfest 2022
  C++/island_count.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#4 Added Check Prime
  C++/Check_Prime.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#6 Quick_Sort_Added
  C++/Quick_Sort_Added
Labels: hacktoberfest, hacktoberfest-accepted

#5 Added Binary To Decimal
  C++/BinaryToDecimal.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#7 Python code ADDED
  Pyhton/fuction.py
Labels: hacktoberfest, hacktoberfest-accepted

#8 Create Binary_search.cpp
  C++/Binary_search.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#10 Decimal to Binary
  C++/Decimal_to_Binary.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest22

#11 Linear Search
  C++/Linear_Search.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest22

#12 merge two sorted arrays program in C++
  C++/Merge_Two_Sorted_Arrays
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest22

#13 Code ADDED
  Javascript/program4.js
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest22

#15 string to roman added
  .DS_Store
  C++/.DS_Store
  C++/stringtoroman.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest22

#14 Create BubbleSort.cpp
  C++/BubbleSort.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest22

#16 Added some basic OOPs program in c++ and tic-tac-toe game in python
  C++/Inheritance.cpp
  C++/towerofhanoi.cpp
  Pyhton/tictactoe.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest22

#31 Added snake.py
  Python/snake.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest22
